spring:
  application:
    name: admin
  profiles:
    active: dev #默认为开发环境
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations:
    - classpath*:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: hospital-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer '  #JWT负载中拿到开头

redis:
  database: hospitalmanagement
  key:
    admin: 'rbac_users'
    resourceList: 'rbac_permissions:resource'
  expire:
    common: 86400 # 24小时

secure:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /admin/login
      - /admin/register
      - /admin/info
      - /admin/logout
      - /minio/upload
      - /alipay/webPay
      - /alipay/**

# OSS相关配置信息
aliyun:
  oss:
    endpoint:  # oss对外服务的访问域名
    accessKeyId:  # 访问身份验证中用到用户标识
    accessKeySecret:  # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName:  # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback:  # 文件上传成功后的回调地
    dir:
      prefix:  # 上传文件夹路径前缀

scan:
  base-packages:
    - com.hospital.common
    - com.hospital.admin
    - com.hospital.security
    - com.hospital.restful.configuration
    - com.hospital.restful.modules
    # - com.hospital.search  # 注释掉表示不启用
    - com.hospital.externalservice

server:
  address: 0.0.0.0
  port: 8080